name: "CD (Entrega/Delivery Continua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

  # VERCEL_TOKEN: "9CYAO1Uo04rZRQfH7yaZG4dj"
  # VERCEL_ORG_ID:  "lFlQ9DaVy6ww2RQAAXd8szB9"
  # VERCEL_PROJECT_ID: "prj_tyrU5WVkKsTX2XBEvDIWQYDh9hAn"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Deploy
        run: |
          npm install
          npm run deploy:prod
